name: Cross-Build

on:
  workflow_dispatch:
  push:
    branches: 
      - master-v4.3

jobs:
  job1:
    name: Build Number
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    steps:
    - name: Generate common build number
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}

  build:
    runs-on: ubuntu-latest
    needs: job1
    strategy:
      matrix:
        platform: [S3-16-o-q-ads]
        depth: [16]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build the firmware
      run: |
        docker pull espressif/idf:release-v4.3
        docker run --rm -v $PWD:/project -w /project espressif/idf:release-v4.3 /bin/bash -c "
          apt-get update && apt-get install -y zip protobuf-compiler && 
          python3 -m pip install protobuf==3.19.6 && 
          
          # 1. Глобальные замены функций
          find components -type f \( -name '*.c' -o -name '*.h' \) -exec sed -i 's/gpio_pad_select_gpio/esp_rom_gpio_pad_select_gpio/g' {} +
          find components -type f \( -name '*.c' -o -name '*.h' \) -exec sed -i 's/ADC_WIDTH_BIT_12/12/g' {} +

          # 2. Лечим ошибку с esp_eth.h (создаем пустую заглушку в системной папке)
          touch /opt/esp/idf/components/esp_eth/include/esp_eth.h

          # 3. Лечим GPIO через CMake. Вставляем в САМОЕ НАЧАЛО файла CMakeLists.txt
          echo 'add_compile_options(-include esp_rom_gpio.h -include soc/gpio_sig_map.h)' > temp_cmake
          cat CMakeLists.txt >> temp_cmake
          mv temp_cmake CMakeLists.txt

          # 4. Фикс rtc_sleep для S3
          echo 'void rtc_sleep_get_default_config(void *cfg) { }' > /opt/esp/idf/components/esp_hw_support/port/esp32s3/rtc_sleep.c

          # 5. Сборка
          rm -rf build sdkconfig
          cp build-scripts/${{ matrix.platform }}-sdkconfig.defaults sdkconfig
          
          # Принудительно гасим Ethernet и Power Management в конфиге
          echo 'CONFIG_ETH_ENABLED=n' >> sdkconfig
          echo 'CONFIG_PM_ENABLE=n' >> sdkconfig
          
          export IDF_TARGET=esp32s3
          idf.py --preview set-target esp32s3
          idf.py build -DDEPTH=${{ matrix.depth }} -DBUILD_NUMBER=${{ needs.job1.outputs.build_number }}
        "

    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}-bin
        path: |
          build/*.bin
          build/bootloader/bootloader.bin
          build/partition_table/partition-table.bin
          build/sdkconfig
